name: Package Application with Pyinstaller (Linux)

on:
  release:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Copy build files
      run: rsync -av --exclude='builds' * builds/linux  
    
    - name: Package Application
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: builds/linux

    - uses: actions/upload-artifact@v2
      with:
        name: BetterCinema-Linux
        path: builds/linux/dist/linux # or path/to/artifact
