name: Package Application with Pyinstaller (Windows)

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Copy build files
      run: rsync -av --exclude='builds' * builds/windows

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: builds/windows

    - uses: actions/upload-artifact@v2
      with:
        name: BetterCinema-Windows
        path: builds/windows/dist/windows # or path/to/artifact

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: builds/windows/dist/windows
        asset_name: app.exe
        tag: ${{ github.ref }}
        overwrite: true