name: Package Application with Pyinstaller (Linux)

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Copy build files
      run: rsync -av --exclude='builds' * builds/linux  
    
    - name: Package Application
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: builds/linux

    - uses: actions/upload-artifact@v2
      with:
        name: BetterCinema-Linux
        path: builds/linux/dist/linux # or path/to/artifact

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: builds/windows/dist/windows
        asset_name: app
        tag: ${{ github.ref }}
        overwrite: true
