name: Package Application with Pyinstaller (Windows)

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Copy build files
      run: rsync -av --exclude='builds' * builds/windows

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: builds/windows

    - uses: actions/upload-artifact@v2
      with:
        name: BetterCinema-Windows
        path: builds/windows/dist/windows # or path/to/artifact

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: builds/windows/dist/windows/app.exe